name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      # Note: CMake and Ninja are installed on GitHub runners by default
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ./build/HW1
      working-directory: ${{github.workspace}}
    
    - name: Run Python Test Script
      run: python Test/test_output.py
      working-directory: ${{github.workspace}}
